spring.application.name=raizes-do-nordeste
spring.datasource.url=jdbc:postgresql://localhost:5432/raizes_do_nordeste
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
